// Custom OpenNext worker: fetch handler + Cloudflare Cron scheduled().
// The `.open-next/worker.js` import is generated at deploy build time.
// @ts-expect-error — generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { publishDueScheduledArticles } from "./lib/cron/publish-scheduled";

type CronEnv = {
  NEXT_PUBLIC_SUPABASE_URL?: string;
  SUPABASE_SECRET_KEY?: string;
};

export default {
  fetch: handler.fetch as (
    request: Request,
    env: CronEnv,
    ctx: unknown,
  ) => Promise<Response> | Response,
  async scheduled(_event: unknown, env: CronEnv) {
    await publishDueScheduledArticles(env);
  },
};
